Repository Cazoo-uk/consent-manager, pull requests merged in 2021-05, with the labels that each got.

#8 copy over circleCI config from cazoo-ui
  .circleci/config.yml
Labels: size/L

#9 bump version
  package.json
Labels: size/XS

#10 bump for release test
  package.json
Labels: size/XS

#11 Chore/remove postpublish step
  package.json
Labels: size/XS

#12 Updated readme
  README.md
Labels: size/M
